# My Solution to Exercise 1

If $x \in S$ and $x \in S^{\bot}$, then $<x,x>=0$, since $S$ and $S^{\bot}$ are orthogonal complements.

But $<x,x>=\|x\|^2$ and $\|x\|^2>0,\forall x \neq 0$.

Thus, $S \cap S^{\bot} = \{0\}$.

# My Solution to Exercise 2

__Symmetry__

Let $X$ be a matrix with dimensions $m \times n$. 

Then, $\underbrace{P}_\text{$m \times m$} = \underbrace{X}_\text{$m \times n$}\underbrace{(X'X)^{-1}}_\text{$n \times n$}\underbrace{X'}_\text{$n \times m$}$. Similarly, for $M = I - P$.

__Idempotence__

$$PP = X\underbrace{(X'X)^{-1}X'X}_\text{I}(X'X)^{-1}X'=X(X'X)^{-1}X'=P$$

$$MM = (I-P)(I-P) = (I-P)I-(I-P)P = II - PI - IP -PP = I - P$$

Intuition is that $P$ is a orthogonal projection onto the subspace $S$ so the distance is already minimized of $\forall x \in S$ such that $P$, also the projection operator, returns itself.

# My Solution to Exercise 3

## Implementation of Gram-Schmidt Orthogonalization Algorithm

In [136]:
import numpy as np
from scipy import linalg as la


def gram_schmidt(X):
    """
    Implements Gram-Schmidt orthogonalization.

    Parameters
    ----------
    X : an m x n array with linearly independent columns

    Returns
    -------
    U : an m x n array with orthonormal columns

    """
    
    # Set up
    m,n = np.shape(X)
    V = np.zeros((m,n))
    U = np.zeros((m,n))

    for i in range(n):
        # Set up
        V[:,i] = X[:,i]
        for j in range(i):
            # Project onto the orthogonal complement
            V[:,i] = V[:,i] - (X[:,i].T @ U[:,j])*U[:,j]
        
        # Normalize
        U[:,i] = V[:,i]/np.sqrt(V[:,i].T @ V[:,i])
    
    return U

In [137]:
y = [1, 3, -3]

X = [[1, 0],
     [0, -6],
     [2, 2]]

X, y = [np.asarray(z) for z in (X, y)]
print(X.shape)
print(y.shape)

(3, 2)
(3,)


In [138]:
Py1 = X @ np.linalg.inv(X.T @ X) @ X.T @ y
Py1

array([-0.56521739,  3.26086957, -2.2173913 ])

In [139]:
U = gram_schmidt(X)
print(U)
print(U.shape)

[[ 0.4472136  -0.13187609]
 [ 0.         -0.98907071]
 [ 0.89442719  0.06593805]]
(3, 2)


In [140]:
Py2 = U @ U.T @ y
Py2

array([-0.56521739,  3.26086957, -2.2173913 ])

In [141]:
from scipy.linalg import qr

Q, R = qr(X, mode='economic')
print(Q)
print(Q.shape)

[[-0.4472136  -0.13187609]
 [-0.         -0.98907071]
 [-0.89442719  0.06593805]]
(3, 2)


In [142]:
Py3 = Q @ Q.T @ y
Py3

array([-0.56521739,  3.26086957, -2.2173913 ])

In [143]:
 np.allclose(Py2, Py3)

True

# Text Solution to Exercise 3

In [144]:
import numpy as np

def gram_schmidt(X):
    """
    Implements Gram-Schmidt orthogonalization.

    Parameters
    ----------
    X : an n x k array with linearly independent columns

    Returns
    -------
    U : an n x k array with orthonormal columns

    """

    # Set up
    n, k = X.shape
    U = np.empty((n, k))
    I = np.eye(n)

    # The first col of U is just the normalized first col of X
    v1 = X[:,0]
    U[:, 0] = v1 / np.sqrt(np.sum(v1 * v1))

    for i in range(1, k):
        # Set up
        b = X[:,i]        # The vector we're going to project
        Z = X[:, 0:i]   # first i-1 columns of X

        # Project onto the orthogonal complement of the col span of Z
        M = I - Z @ np.linalg.inv(Z.T @ Z) @ Z.T
        u = M @ b

        # Normalize
        U[:,i] = u / np.sqrt(np.sum(u * u))

    return U

In [145]:
y = [1, 3, -3]

X = [[1, 0],
     [0, -6],
     [2, 2]]

X, y = [np.asarray(z) for z in (X, y)]

In [146]:
Py1 = X @ np.linalg.inv(X.T @ X) @ X.T @ y
Py1

array([-0.56521739,  3.26086957, -2.2173913 ])

In [147]:
U = gram_schmidt(X)
U

array([[ 0.4472136 , -0.13187609],
       [ 0.        , -0.98907071],
       [ 0.89442719,  0.06593805]])

In [148]:
Py2 = U @ U.T @ y
Py2

array([-0.56521739,  3.26086957, -2.2173913 ])

In [149]:
from scipy.linalg import qr

Q, R = qr(X, mode='economic')
Q

array([[-0.4472136 , -0.13187609],
       [-0.        , -0.98907071],
       [-0.89442719,  0.06593805]])

In [150]:
Py3 = Q @ Q.T @ y
Py3

array([-0.56521739,  3.26086957, -2.2173913 ])

In [151]:
 np.allclose(Py2, Py3)

True